### ISSUE TITLE
This is a Private bot

### ISSUE THREAD

**Issue by vector-co-uz** [alexwbaule/telegramopenwrt#22]
I get "This is a Private bot" messenge every time. Bot scripts not working for me.

Openwrt 22.03.

**Comment by alexwbaule** [comment]
Only the Onwner of the chat started with the bot can send message to him.
This limitation is in here:
https://github.com/alexwbaule/telegramopenwrt/blob/aa57c1c7e3a648c598a77fdb5ccbb105ea29e3c9/sbin/telegram_bot#L54

If you want to use another chat, that don't belongs to you, you can change here and compare with a list of allowed users.

**Comment by vector-co-uz** [comment]
I still owner of my bot.

**Comment by vector-co-uz** [comment]
> Only the Onwner of the chat started with the bot can send message to him. This limitation is in here:
> 
> https://github.com/alexwbaule/telegramopenwrt/blob/aa57c1c7e3a648c598a77fdb5ccbb105ea29e3c9/sbin/telegram_bot#L54
> 
> If you want to use another chat, that don't belongs to you, you can change here and compare with a list of allowed users.

```
config telegramopenwrt 'global'
	option key '5837****37:[********]-8iJl0ryNxjVF_BpEH64'
	option url 'https://api.telegram.org/bot'
	option my_chat_id '5837****37'
	option timeout '60'
	option ignored_macaddrs_file '/etc/telegramopenwrt/macaddr.ignore'

config telegramopenwrt 'ipcam'
	option header_auth '[HEADER AUTH]'
	option ipaddr '[CAMERA IP OR HOSTNAME]'
	option user '[CAMERA USER]'
	option passwd '[CAMERA PASSWD]'

config telegramopenwrt 'smtp'
	option from '[MAIL FROM]'
	option to '[MAIL TO]'

config telegramopenwrt 'television'
	option ipaddr '[TV IP]'
	option sender_name '[Sender Name]'
	option sender_number '[Sender Number]'
	option receiver_name '[Receiver Name]'
	option receiver_number '[Receiver Number]'

config telegramopenwrt 'proxy'
	option http false
	option https false

```

this is my config. i still cant use my bot.
