### ISSUE TITLE
Reboot in loop

### ISSUE THREAD

**Issue by Jonsonmon** [alexwbaule/telegramopenwrt#23]
When running `/reboot` 
after few seconds it sending "Rebooting in 15 seconds..."
then it reboots.

After the reboot is done, it sends again the "Rebooting in 15 seconds..." and rebooting.
And again and again.

I have to stop the telegram service quick to stop the loop...

**Comment by alexwbaule** [comment]
Hi @Jonsonmon 

your version is updated ? 

i changed the behavior when the command is reboot.
It waits for the command to be executed, writes the last ID first, so it can re-read it after reboot.

https://github.com/alexwbaule/telegramopenwrt/blob/master/sbin/telegram_bot#L42

**Comment by Jonsonmon** [comment]
> Hi @Jonsonmon
> 
> your version is updated ?
> 
> i changed the behavior when the command is reboot. It waits for the command to be executed, writes the last ID first, so it can re-read it after reboot.
> 
> https://github.com/alexwbaule/telegramopenwrt/blob/master/sbin/telegram_bot#L42

Sorry for late response.
I'm using latest version.
