### ISSUE TITLE
Script doesn't work with my jsonfilter 2018-02-04-c7e938d6-1 @OpenWrt 21.02.2 r16495-bf0c965af0

### ISSUE THREAD

**Issue by europe1453** [alexwbaule/telegramopenwrt#24]
I've recently installed the latest version on my router @OpenWrt 21.02.2 r16495-bf0c965af0
And i noticed that the script do nothing, but trying to mail a message everytime i try to send a command to bot.
Then i put a new string below line 54 outputting to system logger some variables values in the original script (/sbin/telegram_bot) and find out that 
$origin and $origin_ans variables are everytime have empty values, so nothing works in my case.
Any idea what is wrong, maybe something changed in jsonfilter command in my OpenWRT release?

**Comment by alexwbaule** [comment]
Im using the openwrt 22.03.3 and its working fine. In the 21.02.* works too.

You follow the config item correctly ?

https://github.com/alexwbaule/telegramopenwrt#how-its-works-

**Comment by europe1453** [comment]
> Im using the openwrt 22.03.3 and its working fine. In the 21.02.* works too.
> 
> You follow the config item correctly ?
> 
> https://github.com/alexwbaule/telegramopenwrt#how-its-works-

Hello, Alex!

I've setup a bot, then created a new private channel with me and my bot only. And faced the behaviour i described above.
And it turned out that in my case Telegram API returns no data in tree "message" at all, it answers with "channel_post" instead.
So, i've changed /sbin/telegram_bot to make all things work.

`			origin=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].channel_post.chat.id")
			msg_id=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].channel_post.message_id")
			username=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].channel_post.chat.username")  # optional
			name=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].channel_post.chat.first_name")    # optional
			lastname=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].channel_post.chat.last_name") # optional
			command=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].channel_post.text")
			is_a_cmd=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].channel_post.entities[*].type")
			query_ans=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].callback_query.id")                   # no value when msg sent from channel
			origin_ans=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].callback_query.message.chat.id")    # no value when msg sent from channel
`
Please see full file: https://pastebin.com/JAn4VGZ5

**Comment by europe1453** [comment]
Also, i've corrected a bit more.
In /usr/lib/telegramopenwrt/plugins/wll_list file you assumed that wlan0 is always 2.4Ghz device. But in modern routers it's not the case anymore, i suppose. At least in my Sercomm S1500 wlan0 is 5, wlan1 is 2.4.
So, i've made some changes, based on checking channel number. If it is less than 15 - it is 2.4 device:

`#!/bin/sh

for wifi in wlan0 wlan1
do
        channel=$(ubus -v call iwinfo info '{"device": "'"${wifi}"'"}' | jsonfilter -e @.channel)
        if [ "$channel" -lt "15" ]; then
                echo -en "--------------*${wifi} - 2.4 Ghz*--------------------\n"      
        else
                echo -en "--------------*${wifi} - 5 Ghz*----------------------\n"      
        fi
        # prolly in future need to replace with: ubus call iwinfo assoclist '{"device": "wlan1"}' | jsonfilter -e @.results[*].mac
        macaddr=$(iwinfo ${wifi} assoclist |grep -oE "([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}" | awk '{printf $0 " "}')
        for lease in ${macaddr}
        do
                line=$(cat /tmp/dhcp.leases | grep -i ${lease})
                if [ $? == 0 ]; then
                        echo "${line}" | awk '{gsub( "*","\\*" ); gsub( "_","\\_" ); printf "Device: " $4 "\nIP: " $3 "\nMac: " toupper($2) "\nState: ";system("./get_ping "$4" 1");printf "\n"}'
                else
                        cat /proc/net/arp | grep -i ${lease} | awk '{gsub( "_","\\_" ); printf "IP: " $1 "\nMac: " toupper($4) "\nState: ";system("./get_ping "$1" 1");printf "\n"}'
                fi
                #./get_mac "${lease}" # doesnt work as of 04-2023
                echo -e "=+=+=+=+=+=+=+=+=\n"
        done
        #echo -en "-----------------------------------------------------------\n"
done`

And in get_ip plugin we have to use "wan" interface nowadays. In my case there is no eth0.2 device, but all OWRTs is using wan virtual interface.
so i've changed it to "wan" and script started to work.

Hope all these thing helps and thank very much for your time and efforts developing this project!

**Comment by alexwbaule** [comment]
@europe1453  

Checking the bot documentation, there is no changes in protocol.

 https://core.telegram.org/bots/api#update
 
You are using a Bot or a Channel ? It's works with a bot.

 About the wll_list is based on my router, you can change to you router itens, or you can feel free toc contribute with the code and make a PR.
