### ISSUE TITLE
Typing Forever

### ISSUE THREAD

**Issue by platmdev** [alexwbaule/telegramopenwrt#25]
system log : 
Sun Jun  4 21:14:56 2023 daemon.info telegram_bot[15166]: {"ok": true,"result":{"message_id": 1083, "from":{ "id": , "is_bot": true, "first_name": "", "username": "" }, "chat":{ "id": , "first_name": "", "last_name": "", "username": "", "type": "private" },"date": "1685888128","text": "21:14:54 up 5 min,  load average: 0.86, 0.57, 0.25","entities": []}}
Sun Jun  4 21:14:56 2023 daemon.err sh[15084]: sh: you need to specify whom to kill
Sun Jun  4 21:15:03 2023 daemon.info telegram_bot[15144]: {"ok":true,"result":true}
Sun Jun  4 21:15:10 2023 daemon.info telegram_bot[15144]: {"ok":true,"result":true}
Sun Jun  4 21:15:17 2023 daemon.info telegram_bot[15144]: {"ok":true,"result":true}

**Comment by alexwbaule** [comment]
Please, give me more context.

**Comment by platmdev** [comment]
after send command on bot telegram, bot reply message, but after that bot status is typing..... forever, must be restart bot to stop it.

system log:

Wed Jun  7 19:40:29 2023 daemon.info telegram_bot[5703]: {"ok":true,"result":true}
Wed Jun  7 19:40:30 2023 daemon.info telegram_bot[5793]: {"ok": true,"result":{"message_id": 1205, "from":{ "id": 5858689104, "is_bot": true, "first_name": "", "username": "" }, "chat":{ "id":, "first_name": "", "last_name": "", "username": "", "type": "private" },"date": "1686141630","text": "I can help you to manage and get some informations about your OpenWRT Router. This is the avaliable ","entities": [{ "offset": 115, "length": 10, "type": "bot_command" }]}}
Wed Jun  7 19:40:30 2023 daemon.err sh[3176]: sh: you need to specify whom to kill
Wed Jun  7 19:40:37 2023 daemon.info telegram_bot[5703]: {"ok":true,"result":true}
Wed Jun  7 19:40:44 2023 daemon.info telegram_bot[5703]: {"ok":true,"result":true}

**Comment by alexwbaule** [comment]
The "typing" is started in line 61, and is killed in line 102, with this command:

kill $(ps | grep -v grep | grep typing | awk '{print $1}')

You can do in your router (when typing is running):
ps | grep -v grep | grep typing | awk '{print $1}'

And see if there is a PID.

Whats your router, and openwrt version ?

**Comment by platmdev** [comment]
AMLogic S905X HG680P
OpenWrt 21.02.3

**Comment by platmdev** [comment]
how about this log?
{"ok":true,"result":true}

**Comment by alexwbaule** [comment]
This log its saying that is no "typing" to be killed.
`Wed Jun 7 19:40:30 2023 daemon.err sh[3176]: sh: you need to specify whom to kill
`

Please, do this command to check (when typing is running):

`ps | grep -v grep | grep typing
`

You can do it, log in via SSH in the router.

**Comment by platmdev** [comment]
On System Log:
[https://drive.google.com/file/d/1Tv6ES-HdqveTOWNrkFFlYrzMy2gTRtUB/view?usp=drive_link](url)

**Comment by platmdev** [comment]
root@SANTUY:~# ps | grep -v grep | grep typing
root@SANTUY:~# 

nothing

**Comment by alexwbaule** [comment]
This log is the response from telegram API, its logged in line 108, its ok.

**Comment by alexwbaule** [comment]
> root@SANTUY:~# ps | grep -v grep | grep typing root@SANTUY:~#
> 
> nothing

only "ps" return running processes ?  

The telegram_bot is running now ?

**Comment by alexwbaule** [comment]
You can do:
`/sbin/typing > /tmp/typing.log &`

and:
`ps | grep -v grep | grep typing `

before that, you can kill the typing...

**Comment by platmdev** [comment]
PID TTY          TIME CMD
26901 pts/2    00:00:00 ash
30144 pts/2    00:00:00 ps


yes telegram bot running now

**Comment by platmdev** [comment]
> This log is the response from telegram API, its logged in line 108, its ok.

no problem?

**Comment by alexwbaule** [comment]
You changed the "ps" command, installing some package ? 

my "ps" return is different.

My ps (its from busybox) has this header:

`PID USER       VSZ STAT COMMAND
`

**Comment by platmdev** [comment]
> You changed the "ps" command, installing some package ?
> 
> my "ps" return is different.
> 
> My ps (its from busybox) has this header:
> 
> `PID USER VSZ STAT COMMAND `

how to fix it? i don't know about this different

**Comment by platmdev** [comment]
procps-ng | 3.3.16-3 | ~30.0 KB | procps is a set of command line and full-screen utilities that provide information out of the pseudo-filesystem… 
procps-ng-ps | 3.3.16-3 | ~35.0 KB | Installs the applet ps.

installed on my package

**Comment by alexwbaule** [comment]
Please, you can do:

`for i in $(find / -iname ps); do opkg search $i; done;
`

**Comment by platmdev** [comment]
> Please, you can do:
> 
> `for i in $(find / -iname ps); do opkg search $i; done; `

root@SANTUY: for i in $(find / -iname ps); do opkg search $i; done; 
busybox - 1.33.2-2
root@SANTUY:

**Comment by platmdev** [comment]
in my terminal after login ssh, appears like this:

`BusyBox v1.33.2 (2022-06-20 09:10:24 UTC) built-in shell (ash)`

**Comment by alexwbaule** [comment]
My "ps" is 1.35 

If you run only "ps" return all running process ? 

For me return a lot..

```
root@openwrt:~# ps
  PID USER       VSZ STAT COMMAND
    1 root      1444 S    /sbin/procd
    2 root         0 SW   [kthreadd]
    3 root         0 IW<  [rcu_gp]
    4 root         0 IW<  [rcu_par_gp]
    8 root         0 IW<  [mm_percpu_wq]
    9 root         0 SW   [rcu_tasks_trace]
   10 root         0 SW   [ksoftirqd/0]
   11 root         0 IW   [rcu_sched]
   12 root         0 SW   [migration/0]
   13 root         0 SW   [cpuhp/0]
......
```

**Comment by platmdev** [comment]
how to reinstall ps?

**Comment by alexwbaule** [comment]
You cant.

You can run e paste the output of:
`ps`

here ?

**Comment by platmdev** [comment]
output: 
root@SANTUY: ps
  PID TTY          TIME CMD
20951 pts/2    00:00:00 ps
26901 pts/2    00:00:00 ash

**Comment by alexwbaule** [comment]
Maybe the procps-ng-ps package.

Change the command, run:
`ps ax`

and send here the output

**Comment by platmdev** [comment]
solved:
`kill $(ps -ef | grep -v grep | grep typing | awk '{print $2}')`

**Comment by alexwbaule** [comment]
Your ps in use is not the ps provided by "busybox"...

**Comment by platmdev** [comment]
> Maybe the procps-ng-ps package.
> 
> Change the command, run: `ps ax`
> 
> and send here the output


also solved:
`kill $(ps ax | grep -v grep | grep typing | awk '{print $1}')`

**Comment by platmdev** [comment]
> Your ps in use is not the ps provided by "busybox"...

maybe, thanks for help 👍🏻

**Comment by alexwbaule** [comment]
![Captura de tela de 2023-06-07 10-54-51](https://github.com/alexwbaule/telegramopenwrt/assets/2652837/06339df4-3efc-438e-a263-a2562ccb6786)

**Comment by alexwbaule** [comment]
Maybe i will check the ps command, if point to busybox or no, and change the command to kill.

**Comment by platmdev** [comment]
<img width="697" alt="image" src="https://github.com/alexwbaule/telegramopenwrt/assets/45200916/a6a04795-7550-4e35-93a6-af8814344589">

different

**Comment by alexwbaule** [comment]
Exactly... i will check this, to build the kill... i will open a bug to fix.

**Comment by platmdev** [comment]
how to change this to busybox?

**Comment by alexwbaule** [comment]
@platmdev 

https://github.com/alexwbaule/telegramopenwrt/releases/tag/1.0.5

Fixed.

**Comment by platmdev** [comment]
> @platmdev
> 
> https://github.com/alexwbaule/telegramopenwrt/releases/tag/1.0.5
> 
> Fixed.

ps ax not ps aw

**Comment by alexwbaule** [comment]
> also solved:
> `kill $(ps aw | grep -v grep | grep typing | awk '{print $1}')`

Follow you... LOL

**Comment by alexwbaule** [comment]
@platmdev

https://github.com/alexwbaule/telegramopenwrt/releases/tag/1.0.6

re-Fixed.

**Comment by platmdev** [comment]
> > also solved:
> > `kill $(ps aw | grep -v grep | grep typing | awk '{print $1}')`
> 
> Follow you... LOL

Wkwkwk sorry typo brother, if busybox only ps run perfecly, if not busybox ps ax hihi
