### ISSUE TITLE
Add opkg update and opkg install command

### ISSUE THREAD

**Issue by userosos** [alexwbaule/telegramopenwrt#27]
Add opkg update and opkg install command. Add get interfaces comand and restart interface name.

**Comment by alexwbaule** [comment]
Hi @userosos 

opkg update/install ok, its easy.

Interfaces, you think in  iface , incluiding bridges, etc OR only "wan" and "lan" to restart it ?

**Comment by alexwbaule** [comment]
Released.
https://github.com/alexwbaule/telegramopenwrt/releases/tag/1.1.1

**Comment by userosos** [comment]
> Released. https://github.com/alexwbaule/telegramopenwrt/releases/tag/1.1.1

Thx!
I think about send just to the bot ssh command, Can do it? I think that SSH command will be more good. Because sometimes i need other software on openwrt like wget. Apps like mc or nano will be difficult to do.
