### ISSUE TITLE
constant reboot

### ISSUE THREAD

**Issue by spothz** [alexwbaule/telegramopenwrt#4]
hi friend, can you explain why, after sending the reboot command, the router raises the interface and sends the reboot command again automatically? it turns out that the rocker only loads and reboots again. I ask for help, I do not understand much about this.

**Comment by alexwbaule** [comment]
Shure !!
When the reboot command is send, in the telegram its has a ID. When reboot finish, the bot is getting the same id and execute again the command.
i think that i fixed that, moving the save last_id to begin of the loop, but maybe its don't work.

I wil watch it again

**Comment by spot320** [comment]
thanks, let me know when you fix

**Comment by spot320** [comment]
hi, didn’t fix the reboot problem?

**Comment by tarasifua** [comment]
Just made a fix for it. Please, accept.

**Comment by spothz** [comment]
> Just made a fix for it. Please, accept.

Какой конфиг исправили? А то из вашего сообщения непонятного нечего.

**Comment by tarasifua** [comment]
/usr/lib/telegramopenwrt/plugins/ctx/reboot
`#!/bin/sh

url=$(uci get telegramopenwrt.global.url)
key=$(uci get telegramopenwrt.global.key)
api="$url$key"

source /var/run/bot_vars
offset=$(($offset+1))
/usr/bin/curl -s -k -X GET $api/getUpdates?offset=$offset >/dev/null

sleep 15 && echo "rebooting" | logger -t "telegram_bot" -p daemon.info && /sbin/reboot
`
и
/usr/lib/telegramopenwrt/plugins/ctx/wifi_list
раскомментировать последнюю строчку

**Comment by spothz** [comment]
спасибо вам, проверил все исправно работает.

**Comment by alexwbaule** [comment]
You have the last version ? Because the ID (from telegram) in this version it is saved before the command run, so its safe to do a reboot.

**Comment by tarasifua** [comment]
Yes, I have latest version. But when I had sent reboot command, it reboots my router constantly. I needed to unplug WAN cable and send .../getUpdates telegram api command from my laptop to clear pending updates and stop reboots. I just made pull request with a fix, if you want, you can accept it

**Comment by alexwbaule** [comment]
Here dont shows up the PR. You can send it the PR and i will accept.

https://github.com/tarasifua/telegramopenwrt/commit/700f86e3131f7242f1f21a7377e2ae1467fbf529

That is the Fix ?

**Comment by tarasifua** [comment]
Sent all of them again

**Comment by alexwbaule** [comment]
Tks @tarasifua !

The missing part that do the reboot fix was maded by @nitrotore in this PR.

https://github.com/alexwbaule/telegramopenwrt/pull/11

**Comment by spothz** [comment]
Подскажите пожалуйста, можно ли добавить в бота чтобы он умел отправлять ссылки на установленный aria2 и ссоотвецтвенно их качал на флешку или жёсткий.?

**Comment by rossanoua** [comment]
I got the same issue "constant reboot".
Workaround was to remove the file `/usr/lib/telegramopenwrt/plugins/reboot`.
I see what the problem was fixed...
But how did I get the same behaviour?
Is this was really fixed?

**Comment by alexwbaule** [comment]
Yes, is fixed.

Removing the file, dont solve the problem. You just remove the "reboot plugin", so you cant reboot you router by the bot anymore.

What is the problem.

The router, when reboot, re-read the reboot command when its come alive from reboot.

this PR, plus this:
https://github.com/alexwbaule/telegramopenwrt/blob/aa57c1c7e3a648c598a77fdb5ccbb105ea29e3c9/sbin/telegram_bot#L42

Fixed.
