### ISSUE TITLE
Wifi restart

### ISSUE THREAD

**Issue by tarasifua** [alexwbaule/telegramopenwrt#5]
Hey, can you fix /wifi_enable, /wifi_disable and /wifi_restart functions? As I understand, bot must respond me with a list of wireless devices to choose which of them need to be enabled or disabled. But it doesn't show anything

**Comment by tarasifua** [comment]
Just made a fix for it. Please, accept.

**Comment by alexwbaule** [comment]
Sorry by  the Delay, 

Can you get this commands in your Router ??

```
wireless=$(uci show wireless |grep "default_radio" | grep ssid |grep -oE "[[:digit:]]+.ssid='([[:graph:]]|[[:blank:]])+'" | awk -F ".ssid=" '{gsub(/[\047]|\[|\]/,"");printf "[ {\"callback_data\": \"##CMD##|" $1 "\^" $2 "\" ,\"text\" : \"" $2 ;system("[ \"$(uci -q get wireless.radio"$1".__toggle)\" == \"Disable\" ] && echo -en \" (Disabled)\" || echo -en \" (Enabled)\"") ; print "\"} ],"}')
echo $wireless
```

**Comment by tarasifua** [comment]
I just made pull request with fix. It works perfect, just needed to uncomment commented line

**Comment by tarasifua** [comment]
it shows me next:
`[ {"callback_data": "##CMD##|0^Lab" ,"text" : "Lab (Enabled)"} ], [ {"callback_data": "##CMD##|1^Lab 5G" ,"text" : "Lab 5G (Enabled)"} ],`
when I sent the command, it asks me which of my wifi need to be disabled. I select one of them, it wrotes me that it's disabled, but it's didn'd disable it

**Comment by tarasifua** [comment]
Ok, I found the problem.
`/usr/lib/telegramopenwrt/plugins/actions/wifi_disable` should be:

```
#!/bin/sh
RULE_NUM="$1"
RULE_NAME="$2"
if [ "$RULE_NUM" == "" ]; then
	echo "1|Rule Num Error!!"
	return 1
else
	uci set wireless.radio$RULE_NUM.__toggle='Disable'
	uci set wireless.radio$RULE_NUM.disabled='1'
	uci commit wireless &> /dev/null
	/sbin/wifi &> /dev/null
	echo "1|Radio $RULE_NAME is disabled."
	exit 0
fi
```

`/usr/lib/telegramopenwrt/plugins/actions/wifi_enable`:

```
#!/bin/sh
RULE_NUM="$1"
RULE_NAME="$2" 
if [ "$RULE_NUM" == "" ]; then
	echo "1|Rule Num Error!!"
	return 1
else
	uci set wireless.radio$RULE_NUM.__toggle='Enable'
	uci delete wireless.radio$RULE_NUM.disabled
	uci commit wireless &> /dev/null
	/sbin/wifi &> /dev/null
	echo "1|Radio $RULE_NAME is enabled."
	exit 0
fi
```

and `/usr/lib/telegramopenwrt/plugins/actions/wifi_restart`

```
#!/bin/sh
RULE_NUM="$1"
RULE_NAME="$2"
if [ "$RULE_NUM" == "" ]; then
	echo "1|Rule Num Error!!"
	return 1
else
	uci set wireless.radio$RULE_NUM.__toggle='Disable'
	uci set wireless.radio$RULE_NUM.disabled='1'
	uci commit wireless &> /dev/null
	/sbin/wifi &> /dev/null
	uci set wireless.radio$RULE_NUM.__toggle='Enable'
	uci delete wireless.radio$RULE_NUM.disabled
	uci commit wireless &> /dev/null
	/sbin/wifi &> /dev/null
	echo "1|Radio $RULE_NAME was restarted."
	exit 0
fi
```

**Comment by alexwbaule** [comment]
Send me a PR please. !

**Comment by tarasifua** [comment]
sent
<img width="671" alt="Знімок екрана 2020-09-05 о 09 56 08" src="https://user-images.githubusercontent.com/1798483/92299768-19616900-ef5e-11ea-9e9b-d18eb098b600.png">

**Comment by alexwbaule** [comment]
OK @tarasifua , merged all PRs (except the reboot, fixed by @nitrotore).

Tks again !
